production:
    url: http://127.0.0.1:8984/solr/blacklight-dev
development:
    url: http://127.0.0.1:8984/solr/blacklight-dev
test: &TEST
    url: http://127.0.0.1:8984/solr/blacklight-dev
cucumber:
    <<: *TEST
