production:
    url: http://127.0.0.1:8983/solr/blacklight
development:
    url: http://127.0.0.1:8983/solr/blacklight
test: &TEST
    url: http://127.0.0.1:8983/solr/blacklight
cucumber:
    <<: *TEST
