#!/bin/bash
bundle exec rake solr:marc:index MARC_FILE=spec/fixtures/marc/rrhof.mrc
bundle exec rake rockhall:ead:index EAD=spec/fixtures/ead
bundle exec rake rockhall:pbcore:index PBCORE=spec/fixtures/pbcore
