#!/bin/bash
# EAD rake script
#
# Adam Wead
# Rock and Roll Hall of Fame

# Config

APPDIR="/var/www/rails/catalog"

source ~/.bash_profile
cd $APPDIR
for f in $@
do
  export FILE=$f
  bundle exec rake solr:ead:index
done
exit 0;
