#!/usr/bin/env ruby
require File.expand_path('../../config/boot',  __FILE__)
require "nokogiri"

d = "/mnt/lucille/LIBRARY\&ARCHIVES/EAD"
list = Array.new
Dir.chdir(d)
files = Dir.glob("*.xml")
files.each do |file|
    raw = File.read(file)
    raw.gsub!(/xmlns=".*"/, '')
    xml = Nokogiri::XML(raw)
    
    level = 5
    while level > 0
      xml.xpath("//c0#{level}/odd").each do |node|
        node.element_children.each { |c| list << c.name } 
      end
      level = level - 1
    end
end

puts list.uniq
