#!/bin/bash
RAILS_ENV=test bin/rake rockhall:solr:clean
RAILS_ENV=test bin/rake solr:marc:index MARC_FILE=spec/fixtures/marc/rrhof.mrc
RAILS_ENV=test bin/rake rockhall:ead:index EAD=spec/fixtures/ead
RAILS_ENV=test bin/rake rockhall:pbcore:index PBCORE=spec/fixtures/pbcore